### ISSUE TITLE
[Compatibility/2.8] Area, music select and ooc commands broken.

### ISSUE THREAD

**Issue by raidensnake** [Crystalwarrior/KFO-Server#2]
`[asyncio] base_events@1707 : Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...opus#91##0#%'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...opus#91##0#%'>)>
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 318, in _loop_reading
    self._data_received(data)
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 269, in _data_received
    self._protocol.data_received(data)
  File "C:\test\server\network\aoprotocol.py", line 108, in data_received
    self.net_cmd_dispatcher[cmd](self, args)
  File "C:\test\server\network\aoprotocol.py", line 701, in net_cmd_mc
    getattr(commands, called_function)(self.client, args[0])
  File "C:\test\server\commands\area.py", line 143, in ooc_cmd_area
    raise ArgumentError('Too many arguments. Use /area <id>.')
server.exceptions.ArgumentError: Too many arguments. Use /area <id>.`

**Comment by raidensnake** [comment]
This is what it shows every time I try and do something.

**Comment by Crystalwarrior** [comment]
Which client version?

**Comment by raidensnake** [comment]
the kfo-ao2 version 2.8.4 branch.

**Comment by raidensnake** [comment]
seems like the issue is server side from what I can tell. No idea what's causing it.

**Comment by raidensnake** [comment]
@Crystalwarrior Thanks for posting the new commit. It resolved the problem.
https://github.com/Crystalwarrior/KFO-Server/commit/45aa1905b43a9ba57e5f593784c67451db41a509

**Comment by Crystalwarrior** [comment]
Eyyyy

**Comment by raidensnake** [comment]
I've had to reopen this cause the client is unable to change areas although the music list works.

**Comment by raidensnake** [comment]
`[asyncio] base_events@1707 : Exception in callback _ProactorReadPipeTransport._loop_reading(<_OverlappedF...ng Room#91#%'>)
handle: <Handle _ProactorReadPipeTransport._loop_reading(<_OverlappedF...ng Room#91#%'>)>
Traceback (most recent call last):
  File "C:\test\server\commands\area.py", line 137, in ooc_cmd_area
    area = client.server.area_manager.get_area_by_id(int(args[0]))
ValueError: invalid literal for int() with base 10: 'lounge'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 318, in _loop_reading
    self._data_received(data)
  File "C:\Program Files\Python38\lib\asyncio\proactor_events.py", line 269, in _data_received
    self._protocol.data_received(data)
  File "C:\test\server\network\aoprotocol.py", line 108, in data_received
    self.net_cmd_dispatcher[cmd](self, args)
  File "C:\test\server\network\aoprotocol.py", line 701, in net_cmd_mc
    getattr(commands, called_function)(self.client, args[0])
  File "C:\test\server\commands\area.py", line 142, in ooc_cmd_area
    client.change_area(area)
TypeError: change_area() missing 1 required positional argument: 'hidden'`

**Comment by raidensnake** [comment]
This is what the server is throwing out.

**Comment by raidensnake** [comment]
@Crystalwarrior Everything is fully fixed now! This fixed it! Thanks! https://github.com/Crystalwarrior/KFO-Server/commit/91e96d6434242fa6f4a46f1f578e49b7c31353ef
